version: '3.7'
services:
        jenkins:
                image: jakeevans17/jenkins-docker-gcp
                build: ./
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
                volumes:
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
                        - type: volume
                          source: jenkins-conf
                          target: /var/jenkins_home
volumes:
        jenkins-conf:
